title: Extended Time Calculator
author: John Boniello
email: johnboniello@gmail.com
description: sit for calculator
twitter_username: johnboniello
github_username:  johnboniello

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
